// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSF3FxqJ_2BrZQ_zq9UTMxY5xSLPSSczI',
    appId: '1:213617734222:web:3fddc67194747863aec91f',
    messagingSenderId: '213617734222',
    projectId: 'debo-alert',
    authDomain: 'debo-alert.firebaseapp.com',
    storageBucket: 'debo-alert.firebasestorage.app',
    measurementId: 'G-Q0FG76PB2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF2qIZdYh9u8VJK5jYEMKWgasfFgE_Gvo',
    appId: '1:213617734222:android:2aa15c904d623af5aec91f',
    messagingSenderId: '213617734222',
    projectId: 'debo-alert',
    storageBucket: 'debo-alert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMBRdjxd7vKqLgLl3ggY4TSo9-r7tkl8g',
    appId: '1:213617734222:ios:50033a8e412fb85faec91f',
    messagingSenderId: '213617734222',
    projectId: 'debo-alert',
    storageBucket: 'debo-alert.firebasestorage.app',
    iosBundleId: 'com.Dag.deboalert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMBRdjxd7vKqLgLl3ggY4TSo9-r7tkl8g',
    appId: '1:213617734222:ios:50033a8e412fb85faec91f',
    messagingSenderId: '213617734222',
    projectId: 'debo-alert',
    storageBucket: 'debo-alert.firebasestorage.app',
    iosBundleId: 'com.Dag.deboalert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSF3FxqJ_2BrZQ_zq9UTMxY5xSLPSSczI',
    appId: '1:213617734222:web:a4aa5e5279a214b5aec91f',
    messagingSenderId: '213617734222',
    projectId: 'debo-alert',
    authDomain: 'debo-alert.firebaseapp.com',
    storageBucket: 'debo-alert.firebasestorage.app',
    measurementId: 'G-VY4Z0WFH80',
  );
}
